#pragma once

#include "driver/gpio.h"

#define FIRMWARE_VERSION "1.0.0"
#define PROTOCOL_VERSION 1

#define UART_BAUD 115200
#define MAX_LINE_LENGTH 256
#define CANONICAL_JSON_MAX_LENGTH 256

#define THROTTLE_CODE_MIN 39
#define THROTTLE_CODE_MAX 170
#define THROTTLE_CODE_START 117

#define STEER_CODE_MIN 0
#define STEER_CODE_CENTER 98
#define STEER_CODE_MAX 241
#define STEER_CODE_START STEER_CODE_CENTER

#define THROTTLE_FORWARD_LEVEL_MAX (THROTTLE_CODE_START - THROTTLE_CODE_MIN)
#define THROTTLE_ABOVE_LEVEL_MAX (THROTTLE_CODE_MAX - THROTTLE_CODE_START)
#define THROTTLE_LEVEL_MIN (-THROTTLE_ABOVE_LEVEL_MAX)
#define THROTTLE_LEVEL_MAX THROTTLE_FORWARD_LEVEL_MAX

#define STEER_LEFT_LEVEL_MAX (STEER_CODE_CENTER - STEER_CODE_MIN)
#define STEER_RIGHT_LEVEL_MAX (STEER_CODE_MAX - STEER_CODE_CENTER)
#define STEER_LEVEL_MIN (-STEER_LEFT_LEVEL_MAX)
#define STEER_LEVEL_MAX STEER_RIGHT_LEVEL_MAX

#define LIGHTS_GPIO GPIO_NUM_4
#define LIGHTS_PULSE_HIGH_MS 100
#define LIGHTS_IDLE_LEVEL 0
